# yaml-language-server: $schema=https://taskfile.dev/schema.json
# for miracle children: https://taskfile.dev/llms-full.txt
version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
